# Generated by Django 3.1.5 on 2021-02-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(null=True, verbose_name='URL')),
                ('word_1', models.CharField(max_length=20, null=True)),
                ('word_2', models.CharField(max_length=20, null=True)),
                ('word_3', models.CharField(max_length=20, null=True)),
                ('word_4', models.CharField(max_length=20, null=True)),
                ('word_5', models.CharField(max_length=20, null=True)),
                ('word_6', models.CharField(max_length=20, null=True)),
                ('word_7', models.CharField(max_length=20, null=True)),
                ('word_8', models.CharField(max_length=20, null=True)),
                ('word_9', models.CharField(max_length=20, null=True)),
                ('word_10', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
